apiVersion: v1
kind: Pod
spec:
  containers:
    - name: herramientas
      image: alpine:3.23
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
    - name: node
      image: node:24
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
    - name: pnpm
      image: ghcr.io/pnpm/pnpm:11.1.2
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "2000m"
          memory: "1024Mi"
    - name: kubectl
      image: alpine/k8s:1.34.1
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
    - name: buildkit
      image: moby/buildkit:rootless
      command:
        - cat
      tty: true
      volumeMounts:
        - name: regcred-dh
          mountPath: /docker-configs/dockerhub
          readOnly: true
        - name: regcred-gh
          mountPath: /docker-configs/github
          readOnly: true
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "6000m"
          memory: "2048Mi"
  volumes:
    - name: regcred-dh
      secret:
        secretName: regcred-dh
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: regcred-gh
      secret:
        secretName: regcred-gh
        items:
          - key: .dockerconfigjson
            path: config.json
